scrape_configs:

  - job_name: 'music-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:7080']
#      - targets: ['musicPlayer.musicService:7080']
        labels:
          application: 'music-service'

  - job_name: 'statistics-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:7081']
#      - targets: ['musicPlayer.statisticsService:7081']
        labels:
          application: 'statistics-service'