server:
  port: 9081
spring:
  application:
    name: statistics-service
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
          ttl: 20s
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true