apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://musicPlayer.prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
    orgId: 1
    version: 1